version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Build started on `date`
      - mvn package -Dmaven.test.skip=true
  post_build:
    commands:
      - echo Packaging build artifacts...
      - mkdir -p bundle
      - cp target/*.jar bundle/app.jar
      - echo "web: java -jar app.jar" > bundle/Procfile
artifacts:
  files:
    - bundle/**
  base-directory: bundle
  discard-paths: yes
