version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests
      - cp target/*.jar application.jar
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - application.jar
  discard-paths: yes

